### ISSUE TITLE
When you leave the character and enter again, you

### ISSUE THREAD

**Issue by Anderson0xFF** [EgzoT/-OTClient-Mod-health_and_mana_circle#2]
When you leave the character and enter again, you

![image](https://user-images.githubusercontent.com/23642470/34237056-6433a6aa-e5d9-11e7-84da-e856ea449773.png)

**Comment by EgzoT** [comment]
This is problem with view mode/left panel.
Write in console "print(modules.game_interface.currentViewMode)" and write result here.

**Comment by EgzoT** [comment]
Probably problem is when:
->mode "2"
->change left panel state
->change mode

**Comment by Anderson0xFF** [comment]
![image](https://user-images.githubusercontent.com/23642470/34237462-929e991c-e5db-11e7-9a98-682f503d5e8f.png)
![image](https://user-images.githubusercontent.com/23642470/34237481-a76c3ffc-e5db-11e7-8519-3c1361a50371.png)

**Comment by EgzoT** [comment]
So, if you relogin -> "modules.game_interface.currentViewMode" number was change?

**Comment by Anderson0xFF** [comment]
is because I made some changes in the game interface to get the screen more open if the sidebars

**Comment by EgzoT** [comment]
Probably yes, why?
Because in game is few states who change player position in screen.
1) Resize map -> implemented.
2) Add Left Panel -> implemented.
3) View Mode nr. 2 -> implemented.

So, in yours screen I see that you use state nr. 2 but with name 3. Well you probably must change condition in line 118 from:
if currentViewMode() == 2 then
to:
if currentViewMode() == 2 or currentViewMode() == 3 then

**Comment by Anderson0xFF** [comment]
How can I solve this problem ?

https://pastebin.com/Nc8p1DkS

https://pastebin.com/FRCQpqXN

**Comment by Anderson0xFF** [comment]
okay

**Comment by Anderson0xFF** [comment]
![image](https://user-images.githubusercontent.com/23642470/34237922-efbc4278-e5dd-11e7-90fd-2b075acd9d5a.png)

**Comment by EgzoT** [comment]
Ahh, 2 more line:
In lines 95, 102 (the same code):
Change from:
if currentViewMode() ~= 2 then
to:
if currentViewMode() ~= 2 or currentViewMode() ~= 3 then

**Comment by Anderson0xFF** [comment]
as soon as i get in the game

![image](https://user-images.githubusercontent.com/23642470/34238104-c2bd7f66-e5de-11e7-93fe-bb92182f5521.png)

**Comment by EgzoT** [comment]
Probably, I make mistake with conditions:
- change "and" to "or" in this 3 lines.

**Comment by Anderson0xFF** [comment]
more after you restart the modules goes to the place

**Comment by EgzoT** [comment]
Because it's refresh UI, and draw again this objects.

**Comment by Anderson0xFF** [comment]
complicated
I tried here in every way I know and no results

**Comment by EgzoT** [comment]
In line 118 from:
 if currentViewMode() == 2 then
 to:
 if currentViewMode() == 2 or currentViewMode() == 3 then

In lines 95, 102 (the same code):
 Change from:
 if currentViewMode() ~= 2 then
 to:
 if currentViewMode() ~= 2 or currentViewMode() ~= 3 then

You change "and" to "or"?

**Comment by Anderson0xFF** [comment]
![image](https://user-images.githubusercontent.com/23642470/34238594-458da2d4-e5e1-11e7-8da8-2b5d8eec3cce.png)

**Comment by Anderson0xFF** [comment]
https://pastebin.com/BWU16Lqe

**Comment by EgzoT** [comment]
In lines 92-96 change:
This:

if currentViewMode() ~= 2 or currentViewMode() ~= 3 then
  healthCircleFront:setY(mapPanel:getHeight() / 2 - healthCircle:getHeight() / 2 + 30 + Yhppc)
else
  healthCircleFront:setY(mapPanel:getHeight() / 2 - healthCircle:getHeight() / 2 + 0 + Yhppc)
end

To:

if currentViewMode() == 2 or currentViewMode() == 3 then
  healthCircleFront:setY(mapPanel:getHeight() / 2 - healthCircle:getHeight() / 2 + 0 + Yhppc)
else
  healthCircleFront:setY(mapPanel:getHeight() / 2 - healthCircle:getHeight() / 2 + 30 + Yhppc)
end

**Comment by Anderson0xFF** [comment]
![image](https://user-images.githubusercontent.com/23642470/34239108-fd4992a0-e5e3-11e7-878c-a032d287a0fe.png)

**Comment by EgzoT** [comment]
In lines 105-109 change:

if currentViewMode() ~= 2 or currentViewMode() ~= 3 then
  manaCircleFront:setY(mapPanel:getHeight() / 2 - manaCircle:getHeight() / 2 + 30 + Ymppc)
else
  manaCircleFront:setY(mapPanel:getHeight() / 2 - manaCircle:getHeight() / 2 + 0 + Ymppc)
end

To:

if currentViewMode() == 2 or currentViewMode() == 3 then
  manaCircleFront:setY(mapPanel:getHeight() / 2 - manaCircle:getHeight() / 2 + 0 + Ymppc)
else
  manaCircleFront:setY(mapPanel:getHeight() / 2 - manaCircle:getHeight() / 2 + 30 + Ymppc)
end

**Comment by Anderson0xFF** [comment]
![image](https://user-images.githubusercontent.com/23642470/34254366-81530f22-e62a-11e7-9423-ad6c513e51cc.png)

Obrg :)

**Comment by Anderson0xFF** [comment]
thank you

**Comment by EgzoT** [comment]
Some fixes for custom UI in cf6aa02 .
View mode 2 must be preserved.

**Comment by EgzoT** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/qgc3V44Y/1-test)
